# Generated by Django 3.1.1 on 2020-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201206_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='screen_name',
            field=models.CharField(default='Gordon', max_length=30),
            preserve_default=False,
        ),
    ]
