# Generated by Django 3.1.1 on 2020-09-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_capacity', models.IntegerField(default=2000)),
                ('current_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descr', models.CharField(max_length=1000)),
                ('image_icon', models.CharField(max_length=255)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itemManager.inventory')),
            ],
        ),
    ]
