# Generated by Django 3.1.1 on 2020-11-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('spell', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itemManager.item')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('int', models.IntegerField()),
                ('dex', models.IntegerField()),
                ('str', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('hit_dice', models.IntegerField(default=0)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itemManager.inventory')),
                ('slots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.slot')),
            ],
        ),
    ]
