# Generated by Django 3.1.1 on 2020-09-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='spell',
            field=models.BooleanField(default=False),
        ),
    ]
