# Generated by Django 3.1.1 on 2020-12-20 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='famous_last_words',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='character',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='party.party'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
