# Generated by Django 3.1.1 on 2020-09-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_slot_spell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='slot',
            new_name='slots',
        ),
    ]
