# Generated by Django 3.1.1 on 2020-09-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_hit_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
